shell = "debian"

[env]
term = "xterm-256color"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
# { key = "A", mods = "Control", chars = "tmux new-session -A -s general\n" },
# { key = "G", mods = "Control", chars = "lazygit\n" },
]
